export const GET_CONFIG = "GET_CONFIG";
export const GET_GENRES = "GET_GENRES";

export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_INITIAL = "FETCH_INITIAL";
export const FETCH_MOVIES_BY_GENRE = "FETCH_MOVIES_BY_GENRE";

export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";
